name: ğŸš€ Deploy kubejs folder to the minecraft server

# Controls when the workflow will run
on:
  # ãƒ—ãƒƒã‚·ãƒ¥æ™‚ã«èµ°ã‚‹ã¨æœˆ3000åˆ†ã®ç„¡æ–™æ è¶…ãˆã¡ã‚ƒã†ã‹ã‚‰ã‚³ãƒ¡ãƒ³ãƒˆã‚¢ã‚¦ãƒˆ
  # # Triggers the workflow on push but only for the main branch
  # push:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyftpsync==4.0.0a3
    - name: FTP Deploy
      uses: lujiaying/FTP-Deploy-Action-Py3.9@v1.0
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        passwd: ${{ secrets.FTP_PASSWORD }}
        port: 21
        local_dir: ./kubejs
        remote_dir: /kubejs
        exclude: .git,.github,.DS_Store,README*,LICENSE,.vscode,/config/ftbquests/,/config/fancymenu/
        dry_run: False
